export const categories_profession = [
  {
    id: 1,
    name: "All",
    iconUrl: "https://img.icons8.com/fluency/48/000000/neurodiverse.png",
    count: 564,
  },
  {
    id: 2,
    name: "Languages Teacher",
    iconUrl: "https://img.icons8.com/fluency/48/null/translation.png",
    count: 64,
    suggestedSkills: [
      "Conversational Practice",
      "Exam Preparation",
      "Subject-Specific Tutoring",
      "Homework Assistance",
      "Study Skills Development",
      "Confidence Building",
      "Interview Preparation",
      "Test-Taking Strategies",
      "Public Speaking Training",
      "Project-Based Learning",
      "Creative Writing Guidance",
      "Critical Thinking Exercises",
      "Problem-Solving Skills Training",
      "Group Study Sessions",
      "Time Management Coaching",
      "Custom Lesson Planning",
      "Feedback and Progress Tracking",
      "Interactive Learning Activities",
      "Technological Tools Training",
      "Soft Skills Development",
      "Research and Report Writing",
      "Career Counseling",
      "Presentation Skills Development",
      "Memory Techniques Coaching",
      "Skill Assessment and Analysis"
    ]
    
  },
  {
    id: 3,
    name: "Programmer",
    iconUrl: "https://img.icons8.com/fluency/48/000000/console.png",
    count: 564,
  },
  {
    id: 4,
    name: "Graphics Designer",
    iconUrl: "https://img.icons8.com/fluency/48/000000/design.png",
    count: 164,
  },
  {
    id: 5,
    name: "Video Editor",
    iconUrl: "https://img.icons8.com/fluency/48/000000/video-trimming.png",
    count: 452,
  },
  {
    id: 6,
    name: "Psychologist",
    iconUrl: "https://img.icons8.com/fluency/48/000000/brain.png",
    count: 64,
  },
  {
    id: 7,
    name: "Physicist",
    iconUrl: "https://img.icons8.com/fluency/48/000000/physics.png",
    count: 64,
  },
  {
    id: 8,
    name: "Mathematics",
    iconUrl: "https://img.icons8.com/fluency/48/000000/calculator.png",
    count: 64,
  },
  // { id: 9, name: "Advisor", iconUrl: "https://img.icons8.com/fluency/48/000000/light.png", count: 64 },
  {
    id: 10,
    name: "Religioist",
    iconUrl: "https://img.icons8.com/fluency/48/000000/pray.png",
    count: 64,
  },
  // { id: 11, name: "Astronomer", iconUrl: "https://img.icons8.com/fluency/48/000000/telescope.png", count: 64 },
  {
    id: 12,
    name: "Business",
    iconUrl: "https://img.icons8.com/fluency/48/000000/investment.png",
    count: 64,
  },
  // { id: 13, name: "Traveler", iconUrl: "https://img.icons8.com/fluency/48/000000/passenger-with-baggage.png", count: 964 }, // Uncommented as a popular category
];





export const suggestedProfessions = [
  "English Teacher",
  "Web Developer",
  "Graphic Designer",
  "Video Editor",
  "Psychologist",
  "Software Engineer",
  "Math Tutor",
  "Data Scientist",
  "Digital Marketer",
  "Content Writer",
  "UX/UI Designer",
  "AI/ML Engineer",
  "Mechanical Engineer",
  "Social Media Manager",
  "Financial Analyst",
  "Project Manager",
  "Cybersecurity Specialist",
  "Human Resources Manager",
  "Mobile App Developer",
  "Product Manager",
  "Sales Executive",
  "Business Consultant",
  "Civil Engineer",
  "Biomedical Scientist",
  "Interior Designer",
  "Legal Advisor",
  "Fitness Trainer",
  "Photographer",
  "Chef",
  "Accountant",
  "Translator",
  "Video Game Developer",
  "Music Teacher",
  "Event Planner",
  "Architect",
  "Digital Illustrator",
  "Network Engineer",
  "Economist",
  "SEO Specialist",
  "Customer Support Specialist"
]
