export const usersDataLocal = [
  {
    id: 1,
    userName: "Abdullah Al Kaisan",
    profession: "Web developer",
    avatar:
      "https://pbs.twimg.com/profile_images/1544305803888566272/7uAiIOYR_400x400.jpg",
    hourRate: 2.24,
    isVarified: true,
    isOnline: "",
    followers: 3212,
    rating: 92,
    totalCall: 145,
    flag: "bd",
    gigLanguage: "English",
    languages: ["English", "Bengali", "Hindi"],
    country: "Bangladesh",
    city: "Jamalpur",
    skills: [
      "Javascript",
      "React",
      "MongoDB",
      "Photoshop",
      "Premiere pro",
      "Graphic design",
      "UX UI Design",
      "English",
    ],
  },
  {
    id: 2,
    userName: "John Doe",
    profession: "Software Engineer",
    avatar: `https://lh3.googleusercontent.com/a/ACg8ocKjcLQnbqhz1e6GuIXL1IrBSg2pG_FSAtw-vO1ejOyW890`,
    hourRate: 3.5,
    isVarified: false,
    isOnline: "",
    followers: 50,
    rating: 85,
    totalCall: 100,
    flag: "us",
    gigLanguage: "English",
    languages: ["English", "Spanish"],
    country: "United States",
    city: "New York",
    skills: ["Java", "Spring Boot", "React", "MySQL", "Python", "Django"],
  },
  // Add more users here...
  {
    id: 3,
    userName: "Alice Johnson",
    profession: "Graphic Designer",
    avatar:
      "https://lh3.googleusercontent.com/a/ACg8ocK386pzE7Z-bSFqbGXHYVxxKt5pYh_OAnMnkKWDOPhNabI",
    hourRate: 4.75,
    isVarified: true,
    isOnline: "busy",
    followers: 80,
    rating: 95,
    totalCall: 200,
    flag: "gb",
    gigLanguage: "English",
    languages: ["English", "French"],
    country: "United Kingdom",
    city: "London",
    skills: ["Adobe Illustrator", "Photoshop", "InDesign", "Typography"],
  },
  // More users...
  {
    id: 4,
    userName: "Mohamed Salah",
    profession: "Football Player",
    avatar:
      "https://lh3.googleusercontent.com/a/ACg8ocIdaEDJG7PYFEkpmgPOICdwll5qySj_Q7-PmLwtxHQMroA",
    hourRate: 500,
    isVarified: true,
    isOnline: "",
    followers: 11060600,
    rating: 99,
    totalCall: 5000,
    flag: "eg",
    gigLanguage: "Arabic",
    languages: ["Arabic", "English"],
    country: "Egypt",
    city: "Cairo",
    skills: ["Scoring goals", "Dribbling", "Speed"],
  },
  // More users...
  {
    id: 5,
    userName: "Maria Garcia",
    profession: "Translator",
    avatar:
      "https://lh3.googleusercontent.com/a/ACg8ocKg4H0S4oUQl5TVLe72k5iueHshMcheBvx51rZ_jWm84s4",
    hourRate: 20,
    isVarified: true,
    isOnline: "online",
    followers: 200,
    rating: 88,
    totalCall: 300,
    flag: "id",
    gigLanguage: "Spanish",
    languages: ["Spanish", "English", "French"],
    country: "Indonesia",
    city: "Madrid",
    skills: ["Translation", "Interpreting", "Proofreading"],
  },
  // More users...
  {
    id: 6,
    userName: "Yuki Tanaka",
    profession: "Software Developer",
    avatar: "https://lh3.googleusercontent.com/a/ACg8ocJtYzW14Y0D7PwkgiwSPw7bDe8gJC_FoQFE7A8mP71PRiI",
    hourRate: 2500,
    isVarified: true,
    isOnline: "online",
    followers: 150,
    rating: 90,
    totalCall: 400,
    flag: "jp",
    gigLanguage: "Japanese",
    languages: ["Japanese", "English"],
    country: "Japan",
    city: "Tokyo",
    skills: ["Python", "Django", "React", "Flask", "Machine Learning"],
  },
  // More users...
  {
    id: 7,
    userName: "Elena Petrova",
    profession: "Data Scientist",
    avatar: "https://lh3.googleusercontent.com/a/ACg8ocL1a-xNIqHHXT9L8DLw8U0OHXt4Gwc7erfvuod3d1V-gjw",
    hourRate: 150,
    isVarified: true,
    isOnline: "busy",
    followers: 300,
    rating: 93,
    totalCall: 700,
    flag: "ru",
    gigLanguage: "Russian",
    languages: ["Russian", "English"],
    country: "Russia",
    city: "Moscow",
    skills: ["Python", "R", "Machine Learning", "Statistics"],
  },
  // More users...
  {
    id: 8,
    userName: "Luca Rossi",
    profession: "Chef",
    avatar: "https://lh3.googleusercontent.com/a-/ALV-UjWIDN_JKKo0xpdedARYbEyIV5OMn65BZTELQh6aKgtjEZCdOE0I5kHjIzU_hVZYx98kaDqMDQXxUmDca2MnOrmXlkVBywDVhckPZJ7D6AVuSAYoly3h9W_IrM1liikot8r_bgYtCFh07iAOvkRAbNQEBUx3gGdu8HOlK27OnS2_p4ZMu_GQr0wQWgQ8SJ2DMiZc07L-c04Qx_CpuRJJT2FI0FinC9NFX0mGYRdTcyYpMw7gz5Qsj8_gE0g7NOGRy_DfUcQcfJHQA53OOP4LUbiT4BP1aKpHImSbnd03_w9IbFIq5vSIbEOyD-k9NSMItL9StMOGlZaYRxxw449nuunQGoRHB8chw26BN0nEr1zF_kK_-qdr-v4m2cG--FzT9XSDAM4kvSpJn-53adnvNVSwoIpvNhffrDSr0PAUoRVQavfIdn1DH0TNofjGLt8Y-UlCWSIrsOoeC4LFNZjnAQB08HpqjTKe9WEiDA7QT7qyd-PMUY9q2KHp_N5EsWlNDG22X-Gm6xaPds5u0tgVAD4U7rrLMJ-FOwBWEVzHkHNbQj_uAZCitTbrWVvt_aVac1lJFQC0U9tVypVCZnprYLzj7--B78Uy2cxDrOnZycCSDYRnAAZIQ4nMnqEzuBuotEjFUGU6_fjlLt9hQ87M9DDbD7ESAQ7xnTL-VEJsvITRKQWQX0-mNq5oMFhAsUC82E6DA0Ome5u1xWklR_x37Mkze0EPI5WmB26kcMtyzm9CwZ1ZUQ9VC69WXYuxOgGPPj4lezZEjYdKCutFVnneSxy2U-etmUVVmoCp65oINT0UYz39HLBNWAZskQtTsyoJZZZsg9_zDU3ZwWpfmmUaAT4dDHpHFvVWmsZ4xuVUycc46Up6dKfaDzI_sJ4WjsWp7nARJu3n6t5pFsAtmdtfnVmYHBVYvk2-dzHNjIvArX4vNPe1k3Mb5BIx1yxIuMuXFJM1JtxHXxhbgN-9huI4o_o",
    hourRate: 100,
    isVarified: false,
    isOnline: "online",
    followers: 80,
    rating: 87,
    totalCall: 200,
    flag: "it",
    gigLanguage: "Italian",
    languages: ["Italian", "English"],
    country: "Italy",
    city: "Rome",
    skills: [
      "Italian Cuisine",
      "French Cuisine",
      "Japanese Cuisine",
      "Food Presentation",
    ],
  },
  // More users...
  {
    id: 9,
    userName: "Chen Wei",
    profession: "Translator",
    avatar:
      "https://lh3.googleusercontent.com/a/AAcHTtcQNc4_sXm9UE8VktRqjFBhJiFhif67r99UoKWk0qPzUk8",
    hourRate: 30,
    isVarified: false,
    isOnline: "",
    followers: 120,
    rating: 85,
    totalCall: 250,
    flag: "vn",
    gigLanguage: "Chinese",
    languages: ["Chinese", "English"],
    country: "Vietnam",
    city: "Beijing",
    skills: ["Translation", "Interpreting", "Proofreading"],
  },
  // More users...
  {
    id: 10,
    userName: "Anna Müller",
    profession: "Photographer",
    avatar: "https://lh3.googleusercontent.com/a/ACg8ocJNAjeGBRG_M8eEYVTbBrWw_P3o3SKDcc6uoOiX-SWM8UE",
    hourRate: 50,
    isVarified: false,
    isOnline: "busy",
    followers: 50,
    rating: 80,
    totalCall: 150,
    flag: "de",
    gigLanguage: "German",
    languages: ["German", "English"],
    country: "Germany",
    city: "Berlin",
    skills: ["Portrait Photography", "Landscape Photography", "Photo Editing"],
  },
  // More users...
  {
    id: 11,
    userName: "Purno",
    profession: "Video Editor",
    avatar:
      "https://lh3.googleusercontent.com/a/ACg8ocJJD54sQONqFJ2SdyfXr-VuaRK-In5C3kOpkuPrann2eGs",
    hourRate: 50,
    isVarified: false,
    isOnline: "online",
    followers: 50,
    rating: 80,
    totalCall: 150,
    flag: "bd",
    gigLanguage: "Bengali",
    languages: ["Bengali"],
    country: "Bangladesh",
    city: "Jamalpur",
    skills: ["Premere pro", "Video editor", "Photoshop", "Advisor"],
  },
];
  