export const usersDataLocal = [
    {
      id: 1,
      userName: "Abdullah Al Kaisan",
      profession: "Web developer",
      avatar: "https://pbs.twimg.com/profile_images/1544305803888566272/7uAiIOYR_400x400.jpg",
      hourRate: 2.24,
      followers: 3212,
      rating: 92,
      totalCall: 145,
      flag: "bd",
      gigLanguage: "English",
      languages: ["English", "Bengali", "Hindi"],
      country: "Bangladesh",
      city: "Jamalpur",
      skills: ["Javascript", "React", "MongoDB", "Photoshop", "Premiere pro", "Graphic design", "UX UI Design", "English"]
    },
    {
      id: 2,
      userName: "John Doe",
      profession: "Software Engineer",
      avatar: `https://i.pravatar.cc/300?img=2`,
      hourRate: 3.5,
      followers: 50,
      rating: 85,
      totalCall: 100,
      flag: "us",
      gigLanguage: "English",
      languages: ["English", "Spanish"],
      country: "United States",
      city: "New York",
      skills: ["Java", "Spring Boot", "React", "MySQL", "Python", "Django"]
    },
    // Add more users here...
    {
      id: 3,
      userName: "Alice Johnson",
      profession: "Graphic Designer",
      avatar: "https://i.pravatar.cc/300?img=3",
      hourRate: 4.75,
      followers: 80,
      rating: 95,
      totalCall: 200,
      flag: "gb",
      gigLanguage: "English",
      languages: ["English", "French"],
      country: "United Kingdom",
      city: "London",
      skills: ["Adobe Illustrator", "Photoshop", "InDesign", "Typography"]
    },
    // More users...
    {
      id: 4,
      userName: "Mohamed Salah",
      profession: "Football Player",
      avatar: "https://i.pravatar.cc/300?img=4",
      hourRate: 500,
      followers: 11060600,
      rating: 99,
      totalCall: 5000,
      flag: "eg",
      gigLanguage: "Arabic",
      languages: ["Arabic", "English"],
      country: "Egypt",
      city: "Cairo",
      skills: ["Scoring goals", "Dribbling", "Speed"]
    },
    // More users...
    {
      id: 5,
      userName: "Maria Garcia",
      profession: "Translator",
      avatar: "https://i.pravatar.cc/300?img=5",
      hourRate: 20,
      followers: 200,
      rating: 88,
      totalCall: 300,
      flag: "es",
      gigLanguage: "Spanish",
      languages: ["Spanish", "English", "French"],
      country: "Spain",
      city: "Madrid",
      skills: ["Translation", "Interpreting", "Proofreading"]
    },
    // More users...
    {
      id: 6,
      userName: "Yuki Tanaka",
      profession: "Software Developer",
      avatar: "https://i.pravatar.cc/300?img=6",
      hourRate: 2500,
      followers: 150,
      rating: 90,
      totalCall: 400,
      flag: "jp",
      gigLanguage: "Japanese",
      languages: ["Japanese", "English"],
      country: "Japan",
      city: "Tokyo",
      skills: ["Python", "Django", "React", "Flask", "Machine Learning"]
    },
    // More users...
    {
      id: 7,
      userName: "Elena Petrova",
      profession: "Data Scientist",
      avatar: "https://i.pravatar.cc/300?img=7",
      hourRate: 150,
      followers: 300,
      rating: 93,
      totalCall: 700,
      flag: "ru",
      gigLanguage: "Russian",
      languages: ["Russian", "English"],
      country: "Russia",
      city: "Moscow",
      skills: ["Python", "R", "Machine Learning", "Statistics"]
    },
    // More users...
    {
      id: 8,
      userName: "Luca Rossi",
      profession: "Chef",
      avatar: "https://i.pravatar.cc/300?img=8",
      hourRate: 100,
      followers: 80,
      rating: 87,
      totalCall: 200,
      flag: "it",
      gigLanguage: "Italian",
      languages: ["Italian", "English"],
      country: "Italy",
      city: "Rome",
      skills: ["Italian Cuisine", "French Cuisine", "Japanese Cuisine", "Food Presentation"]
    },
    // More users...
    {
      id: 9,
      userName: "Chen Wei",
      profession: "Translator",
      avatar: "https://i.pravatar.cc/300?img=9",
      hourRate: 30,
      followers: 120,
      rating: 85,
      totalCall: 250,
      flag: "cn",
      gigLanguage: "Chinese",
      languages: ["Chinese", "English"],
      country: "China",
      city: "Beijing",
      skills: ["Translation", "Interpreting", "Proofreading"]
    },
    // More users...
    {
      id: 10,
      userName: "Anna Müller",
      profession: "Photographer",
      avatar: "https://i.pravatar.cc/300?img=10",
      hourRate: 50,
      followers: 50,
      rating: 80,
      totalCall: 150,
      flag: "de",
      gigLanguage: "German",
      languages: ["German", "English"],
      country: "Germany",
      city: "Berlin",
      skills: ["Portrait Photography", "Landscape Photography", "Photo Editing"]
    },
    // More users...
    {
      id: 10,
      userName: "Purno",
      profession: "Video Editor",
      avatar: "https://scontent.fzyl2-2.fna.fbcdn.net/v/t39.30808-1/426198184_3973612782866065_2617325717917228900_n.jpg?stp=c0.0.160.160a_dst-jpg_p160x160&_nc_cat=111&ccb=1-7&_nc_sid=11e7ab&_nc_ohc=TOTXu5qDmSIAX9VL7dv&_nc_ht=scontent.fzyl2-2.fna&oh=00_AfBUng0s8S5DS07mXLgTAtHuGENOqtWV6k9R0PMpSll_vA&oe=65E58FED",
      hourRate: 50,
      followers: 50,
      rating: 80,
      totalCall: 150,
      flag: "bd",
      gigLanguage: "Bengali",
      languages: ["Bengali"],
      country: "Bangladesh",
      city: "Jamalpur",
      skills: ["Premere pro", "Video editor", "Photoshop", "Advisor"]
    }
  ];
  